\documentclass[]{beamer}
\usetheme{Warsaw}

\author{Stephen Gardiner}
\date{November 2008}
\title{Quality Control for Graphics in R}
\institute{Department of Statistics, University of Auckland}

\begin{document}

\frame{\titlepage}

\section[Outline]{}
\frame{\tableofcontents}

\section{Introduction}
\label{sec:introduction}

\begin{frame}[containsverbatim]
  \frametitle{Title}
  \framesubtitle{Subtitle}
@
<<oneToTen>>=

1:10

@
\end{frame}

\end{document}
